#!/bin/bash
# Electron dependency
sudo apt install libgconf-2-4
VERSION=0.4.4
FILE_NAME=Popcorn-Time-$VERSION-linux64.zip
mkdir -p /tmp/Popcorn-Time/
cd /tmp/Popcorn-Time/
wget "https://github.com/popcorn-official/popcorn-desktop/releases/download/v$VERSION/$FILE_NAME"
unzip $FILE_NAME
rm $FILE_NAME
mkdir -p ~/opt
rm -rf ~/opt/Popcorn-Time
mv /tmp/Popcorn-Time ~/opt/Popcorn-Time

mkdir -p ~/.local/share/applications
echo "[Desktop Entry]
Name=Popcorn-Time
Exec=$HOME/opt/Popcorn-Time/Popcorn-Time
Type=Application
StartupNotify=true
Path=$HOME/opt/Popcorn-Time/
Icon=$HOME/opt/Popcorn-Time/src/app/images/icon.png
" > ~/.local/share/applications/PopcornTime.desktop
chmod 755  ~/.local/share/applications/PopcornTime.desktop
